name: 'Elm Lint'
description: 'Lints the Elm code using elm-review and elm-format'
extra-path:
    description: 'Extra paths to be linted'
    required: false
runs:
  using: "composite"
  steps:
     - name: Install dependencies
       run: yarn install
       shell: bash

     - name: Run linter
       run: npx elm-format --validate src ${{ inputs.extra-path }}
       shell: bash

     - name: Run elm-review
       run: npx elm-review --template PaackEng/elm-review-config src ${{ inputs.extra-path }}
       shell: bash
