name: 'Elm Lint'
description: 'Lints the Elm code using elm-review and elm-format'
path:
    description: 'Path or paths to be linted'
    required: false
    default: 'src'
runs:
  using: "composite"
  steps:
     - name: Install dependencies
       run: yarn install

     - name: Run linter
       run: npx elm-format --validate ${{ inputs.path }}

     - name: Run elm-review
       run: npx elm-review ${{ inputs.path }}
