name: 'Elm Validate'
description: 'Runs Elm through elm-format and elm-review then compiles it'
extra-path:
    description: 'Extra paths to be validated'
    required: false
runs:
  using: "composite"
  steps:
     - name: Install dependencies
       run: yarn install
       shell: bash

     - name: Run linter
       run: npx elm-format --validate src ${{ inputs.extra-path }}
       shell: bash

     - name: Run elm-review
       run: npx elm-review --template PaackEng/elm-review-config src ${{ inputs.extra-path }}
       shell: bash

     - name: Validate code
       run: npx elm make src/Main.elm --output /dev/null
       shell: bash
